### ISSUE TITLE
How many have actually just fronted their website with cloudflare?

### ISSUE THREAD

**Issue by nicholasgriffintn** [wordpressenginetracker/wordpressenginetracker.github.io#15]
I ran a dns check on a few of the recent ones and they came back as only having a records and names that correlate to cloudflare, so not sure how you did any detection on that... that's is if you're using DNS like Matt claims.

**Comment by nullfekt** [comment]
All of WP Engine's sites have an `x-powered-by` header that's publicly available, even if proxied through Cloudflare. Pretty basic stuff for anyone that's been on the Internet.

**Comment by nicholasgriffintn** [comment]
> All of WP Engine's sites have an `x-powered-by` header that's publicly available, even if proxied through Cloudflare. Pretty basic stuff for anyone that's been on the Internet. 

And if that's been removed? You can remove headers from a proxy, pretty basic stuff for anyone that's been on the internet.

**Comment by mbabker** [comment]
> so not sure how you did any detection on that... that's is if you're using DNS like Matt claims

Matt has [also stated](https://x.com/photomatt/status/1841394890875212014) that he has a list of every public website powered by WordPress.  Therefore, it is not hard to believe that in his capacity as the sole owner of the `wordpress.org` domain, he has shared the data that the WordPress software sends to his personal website with Automattic, and in his role as CEO, directed employees to use this data to publish this website.  Given that the source code for many of the API endpoints that the WordPress software "phones home" to is not published as part of the public https://github.com/WordPress/wordpress.org repository, it is impossible for anyone to independently audit how that data is (mis-)used.

**Comment by nullfekt** [comment]
> And if that's been removed? You can remove headers from a proxy, pretty basic stuff for anyone that's been on the internet.

Likely wouldn't be tracked as a site on WP Engine as part of this project. Find one in the list that's removed that header. 

Domain names are public. You can download an entire list of every single registered domain name if you wanted, write a script to run them all through cURL, log the header, and filter after.

**Comment by nullfekt** [comment]
You wanted to know how they are detecting it's hosted on WPE when proxied through Cloudflare and I gave you the answer. WPE publicly provides that info. Parsing through logs via "phone home" conspiracies floating around would be more tedious than scripting cURL requests against every known registered domain to get an initial WPE hosted list.

Once you have a list, it's not sophisticated to determine a site is no longer on WPE when 1) You no longer see WPE's headers and 2) You see headers specific to a new host. 

Removing the `x-powered-by` header alone likely wouldn't remove the domain from the list, nor would it track it as being moved to a new host if the headers for the host's they are tracking are not returned. 

You could diff the initial CSV against the current to have a list of all the sites that moved and check them manually yourself if you're bored.
