### ISSUE TITLE
Logarithmic scale graph

### ISSUE THREAD

**Issue by HarrisonTF** [wordpressenginetracker/wordpressenginetracker.github.io#17]
It would be more useful to show the graph as a logarithmic scale graph, a graph type more commonly used for what is essentially exponential growth in the way you're showing this data.

**Comment by nemobis** [comment]
> what is essentially exponential growth

Uh? It's very much linear.

![Schermata_20241111_152937](https://github.com/user-attachments/assets/0c0bb098-7f39-4d0e-aaea-2acfbf4b959b)

**Comment by HarrisonTF** [comment]
apologies, I worded it incorrectly - the current graph shows an ever increasing total, which is fine for a cursory look. 

what could be more useful is:

1. daily changes (although that is dependent on how robust their data scraping is, against a given day's update to the json)
![Screenshot 2024-11-11 at 13 39 41](https://github.com/user-attachments/assets/ac14d281-c057-486a-a3d7-d65d69725836)

2. rate of changes
![Screenshot 2024-11-11 at 13 45 07](https://github.com/user-attachments/assets/e329fbbf-a23d-415a-a085-bb29b1fddfec)

**Comment by wordpressenginetracker** [comment]
Thanks for the idea. We considered both of those, but decided to ship the graph of our count of sites still on WP-Engine. See https://wordpressenginetracker.com/
