### ISSUE TITLE
Moving to Non-WordPress hosts

### ISSUE THREAD

**Issue by HarrisonTF** [wordpressenginetracker/wordpressenginetracker.github.io#18]
Your json data, especially your hosts file, makes no mention of non-WordPress hosts/platforms where domains could also be moved to, for example: Wix, SquareSpace, SquareOnline, Ghost, or WebFlow amongst others. Anecdotally, on social media we hear that this is happening, and it seems to me that you could/should be tracking this too.

As we have no sight of your source data or your methodology for scraping it it is not clear whether you are able to track sites that move OFF WordPress as a platform completely or whether you are simply cherry picking the hosts that support WordPress as a platform and are either Automattic's own assets or close partners of Automattic.

**Comment by wordpressenginetracker** [comment]
Thanks for the idea. We have been watching this, but only see about 2-3% of the moved sites confirmed to be on another CMS. We're keeping an eye on it.
