### ISSUE TITLE
Domain removal from the CSV?

### ISSUE THREAD

**Issue by simplistik** [wordpressenginetracker/wordpressenginetracker.github.io#20]
Are we able to put in some sort of request that removes our clients or domains we own to be removed from that CSV? 

Whether the request is private or public or maybe even creating an appropriate pull request, whatever the method doesn't matter to me.

Respectfully

**Comment by scottlee** [comment]
It can be safely assumed that several of these sites are for internal use only. Not that any malicious actor couldn't monitor domain registrations, but still, I'd like a mechanism for removing URLs.

**Comment by simplistik** [comment]
It does actively expose staging and development URLs which many people assume should be hard-ish to discover. A lot people also don't put these URLs behind any type of protection for simplicity for their client(s).

![image](https://github.com/user-attachments/assets/20512c22-f2b8-4626-af64-03b01f6fee34)

**Comment by Daniel15** [comment]
> many people assume should be hard-ish to discover

For what it's worth, the domains are likely already visible in certificate transparency logs. Every TLS certificate that's issued is logged, and there's several sites to search these logs. For example, you can use this search to find all active certificates for subdomains of `.github.com`: https://crt.sh/?Identity=%25.github.com&exclude=expired. The only way to avoid that is by using a wildcard certificate (e.g. if you have a certificate for `*.staging.example.com` and use a subdomain for every client's staging site).

**Comment by simplistik** [comment]
@Daniel15 yup I know and agree, but this is “curated”.

**Comment by wordpressenginetracker** [comment]
Thanks for asking @simplistik.

If you have domains you would like to remove please go ahead and list them on this issue or contact wp.com support. If you are looking to remove your domains from this sort of tracking you may also want to remove them from https://trends.builtwith.com/websitelist/WP-Engine and other similar services.

We did also remove the domains that start with "staging." and "staging-". There were 932 of them total.

**Comment by simplistik** [comment]
@wordpressenginetracker thanks for taking a look into that. My biggest concern was just amongst the broader scope of staging, dev, beta, alpha or whatever else you might call them being exposed when they probably shouldn't be. I think production sites are fair game.

I've attached some screenshots of a few extra prefixes that you could take into consideration.

Aside from that I think you guys can just do what you're doing. I'll take a look at builtwith too and see what they say.

Again, thanks again for being open to this suggestion.

![image](https://github.com/user-attachments/assets/1e8e0017-23ae-4780-b358-48a9ff05f421)

![image](https://github.com/user-attachments/assets/29940207-fd66-49e7-bf7f-357c774622c6)

![image](https://github.com/user-attachments/assets/0bb3ea22-4645-42af-ab73-781212d9d744)

![image](https://github.com/user-attachments/assets/d435ba0a-4167-45ed-936b-1d6cd6ebe4b9)

**Comment by wordpressenginetracker** [comment]
Yep, those all makes sense. Thanks.

Moved another 1,012 "stg.*", "dev.*", "beta.*", and most of the "dev-*" sites out ("dev-" gets used as a prefix in a lot of domain names it seems).

**Comment by nclm** [comment]
There are also domain using `-dev` (460), or `-staging` (216), or `-stg` (135), or `-beta` (10), etc etc, there are dozens of ways for people to mark work-in-progress pages. You can’t get them all. Many of the ones in `.wpengine.com` are also not meant to be public (domain not bought or connected yet. This whole list is an aberration really, but at least more care could have been put into not revealing private websites. You should also have checked each website’s robots.txt to figure out whether or not they consent to be indexed anywhere.

**Comment by stephcathoh** [comment]
This entire project is problematic. The dev sites should never have been included. To me, any site (production or dev, stg etc.) whose domain owner requests a removal should be removed from the CSV files and from any mentions here.

**Comment by nullfekt** [comment]
>   more care could have been put into not revealing private websites. You should also have checked each website’s robots.txt and equivalent HTTP header to figure out whether or not they consent to be indexed anywhere.

Sounds like your gripe is more with whoever made the sites public if they are intended to be private. The Internet is not private, but HTTP Basic Auth can go a long way.

**Comment by wordpressenginetracker** [comment]
Thanks @nclm. Just removed 288 `*-dev.*.*`, 128 `*-staging*.*`, 120 `*-stg*.*`, and 4 `*-beta*.*`. We're only removing the cases with matching subdomains which I think is why your numbers are a bit higher.

We're still looking into the remaining `.wpengine.com` cases (we've removed about 300k, but there are about 1.6k still there). They seem to be related to redirected domains which are then pointing to the site (possibly misconfigured DNS).

> To me, any site (production or dev, stg etc.) whose domain owner requests a removal should be removed from the CSV files and from any mentions here.

@stephcathoh that's why we're keeping this issue open. So far we've had one person request specific sites and otherwise we've just been proactively removing things that look like staging sites.

To repeat @nullfekt, if a site really wants to be private it should have authentication. All of the listed sites are giving a 200 HTTP response.

**Comment by bradbenj** [comment]
this is just so sad. my clients haven't been successful in getting removed from this list of grievances. sure, have your little project on github- but why store the data here too?

**Comment by bradbenj** [comment]
> Thanks for asking @simplistik.
> 
> If you have domains you would like to remove please go ahead and list them on this issue or contact wp.com support. If you are looking to remove your domains from this sort of tracking you may also want to remove them from https://trends.builtwith.com/websitelist/WP-Engine and other similar services.
> 
> We did also remove the domains that start with "staging." and "staging-". There were 932 of them total.



> > more care could have been put into not revealing private websites. You should also have checked each website’s robots.txt and equivalent HTTP header to figure out whether or not they consent to be indexed anywhere.
> 
> Sounds like your gripe is more with whoever made the sites public if they are intended to be private. The Internet is not private, but HTTP Basic Auth can go a long way.

fantastic point. my gripe is with whoever listed the sites here when they weren't intended to be private or use HTTP Basic Auth.
