### ISSUE TITLE
Moving to Non-WordPress hosts

### ISSUE THREAD

**Issue by HarrisonTF** [wordpressenginetracker/wordpressenginetracker.github.io#27]
Your json data, especially your hosts file, makes no mention of non-WordPress hosts/platforms where domains could also be moved to, for example: Wix, SquareSpace, SquareOnline, Ghost, or WebFlow amongst others

https://github.com/wordpressenginetracker/wordpressenginetracker.github.io/issues/18#issue-2649087456

     Thanks for the idea. We have been watching this, but only see about 2-3% of the moved sites confirmed to be on another CMS. We're keeping an eye on it.

_Originally posted by @wordpressenginetracker in https://github.com/wordpressenginetracker/wordpressenginetracker.github.io/issues/18#issuecomment-2489533675_

In your data you're showing hosts that are far far less than that percentage. 2-3% of the 21,000 sites that your data has recorded as having moved so far would be 640 sites - in your site json this would put them between "Kinsta": 1113, and "Hostinger": 618. I appreciate that this would be lower for individual providers like WiX and Squarespace when taken individually, but it arguably more statistically relevant than say WordPress.com, OVH, IONOS etc whose figures of inbound sites are much smaller.

One of the concerns I hear in the wider WordPress community is that this kerfuffle is putting clients off WordPress entirely. Tracking this would be useful, not just for us out here staring open-mouthed at your antics, but also for yourselves in your echo-chamber internally. 

Could you have a rethink on this please?

**Comment by wordpressenginetracker** [comment]
> One of the concerns I hear in the wider WordPress community is that this kerfuffle is putting clients off WordPress entirely. 

Appreciate your concern here, and we just aren't seeing that in the data.

2-3% across all the non-WP hosts. The top one is (not surprisingly) Shopify and that is at 162 out of the 21,699 sites that have moved (0.7% of the total). Squarespace is 131 and Wix is 94. Also about 26 Drupal sites and a few in the single digits. That is 1.9% of the total. There are a lot of CMSs so we're likely missing some smaller cases so out of caution I put the range going up to 3%.
