### ISSUE TITLE
Trademarks

### ISSUE THREAD

**Issue by Daniel15** [wordpressenginetracker/wordpressenginetracker.github.io#5]
Part of the Automattic v WP Engine debate is around improper usage of trademarks, yet this site is using WP Engine's trademark without permission. 🤔

**Comment by picard102** [comment]
So you're stating that you believe the WP in WP Engine means WordPress then?

**Comment by Daniel15** [comment]
What else would it mean?

**Comment by picard102** [comment]
WP Engine's defence is they claim it's not.

**Comment by Daniel15** [comment]
Even if it's legally okay, it's morally questionable given WP Engine's use of the WordPress trademark would also be considered fair use, yet that's one of the reasons Matt/Automattic is suing WP Engine.

**Comment by picard102** [comment]
> Even if it's legally okay, it's morally questionable given WP Engine's use of the WordPress trademark would also be considered fair use, yet that's one of the reasons Matt/Automattic is suing WP Engine.

WP Engine is the one suing people here. Matt sent a cease and desist.

**Comment by Daniel15** [comment]
> > Even if it's legally okay, it's morally questionable given WP Engine's use of the WordPress trademark would also be considered fair use, yet that's one of the reasons Matt/Automattic is suing WP Engine.
> 
> WP Engine is the one suing people here. Matt sent a cease and desist.

Ah, my mistake, thanks for the correction! It's still something that's come up as part of all this stuff. Matt was unhappy with WP Engine using the "WordPress" trademark on their site.

**Comment by gkennedy87** [comment]
You can find all of the submitted claims and supporting evidence here: ([WPEngine v Automattic](https://www.courtlistener.com/docket/69221176/wpengine-inc-v-automattic-inc/))

**Comment by picard102** [comment]
> > > Even if it's legally okay, it's morally questionable given WP Engine's use of the WordPress trademark would also be considered fair use, yet that's one of the reasons Matt/Automattic is suing WP Engine.
> > 
> > 
> > WP Engine is the one suing people here. Matt sent a cease and desist.
> 
> Ah, my mistake, thanks for the correction! It's still something that's come up as part of all this stuff. Matt was unhappy with WP Engine using the "WordPress" trademark on their site.

No problem.

**Comment by wordpressenginetracker** [comment]
Also answered in https://github.com/wordpressenginetracker/wordpressenginetracker.github.io/issues/6#issuecomment-2463080756

**Comment by jonolds** [comment]
@picard102 is there anywhere that you don't get downvoted into oblivion?
