### ISSUE TITLE
Mangled history?

### ISSUE THREAD

**Issue by Anti-matt-ic** [wordpressenginetracker/wordpressenginetracker.github.io#7]
Curious as to why the branch history [is repeatedly getting clobbered](https://github.com/wordpressenginetracker/wordpressenginetracker.github.io/commits?author=wordpressenginetracker&since=2024-11-07&until=2024-11-07), with Allan's contributions reallocated?

Why is each push rewriting history now?

**Comment by Daniel15** [comment]
My guess is that this is intentional to remove his name from the repo.

**Comment by Anti-matt-ic** [comment]
@Daniel15 certainly one possibility. The associated merge commits are now orphaned.

I'm more concerned about each push replacing the CSV's entire commit history with new commits each hour. It makes the changes considerably more convoluted to track, and enables the maintainer to effectively retcon whatever data they care to, if we do not.

**Comment by Daniel15** [comment]
Yeah, that's definitely an issue. The code that generates the data is not in the repo though, so we have no way to tell if the data is even reliable. The history already has limited usefulness if none of it is verifiable. (great data for WP Engine to use in their lawsuit though, as the site is essentially tracking their damages)

**Comment by DanielRuf** [comment]
The last commit was 11 minutes ago and did not replace all previous commits. They probably fixed their script.

**Comment by DanielRuf** [comment]
There are still forks from before the force-push: https://github.com/wordpressenginetracker/wordpressenginetracker.github.io/forks

**Comment by Anti-matt-ic** [comment]
> The last commit was 11 minutes ago and did not replace all previous commits. They probably fixed their script.

That makes me happy - thanks for the callout. I'll close this next hour.

**Comment by Anti-matt-ic** [comment]
> Yeah, that's definitely an issue. The code that generates the data is not in the repo though, so we have no way to tell if the data is even reliable. The history already has limited usefulness if none of it is verifiable. (great data for WP Engine to use in their lawsuit though, as the repo is essentially tracking their damages over time)

Oh certainly - I don't make any claim to the veracity of the data. There's just of a data hoarder in me that's worried that I might want to look at this all more thoroughly at a later date for as of yet unknown reasons 🙃

**Comment by Anti-matt-ic** [comment]
The behavior appears to have been corrected. Thank you 👍
